name: Deploy to Clojars

on:
  # Manual trigger for releasing/deploying
  workflow_dispatch:
  # Trigger when the Checks workflow completes
  workflow_run:
    workflows: ["Checks"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Clojars
    runs-on: ubuntu-latest
    # Only proceed for:
    # - manual dispatch (always deploy when manually triggered)
    # - or when Checks workflow completed successfully on master and commit message contains '[deploy]'
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'master' &&
       contains(github.event.workflow_run.head_commit.message, '[deploy]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: latest
          lein: 2.9.10
          bb: latest
          clj-kondo: 2023.05.18
          cljfmt: 0.10.4

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t color-tools-deploy .

      - name: Deploy to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: |
          docker run --rm \
            -e CLOJARS_USERNAME="$CLOJARS_USERNAME" \
            -e CLOJARS_PASSWORD="$CLOJARS_PASSWORD" \
            color-tools-deploy \
            clojure -T:build deploy